settings:
  subscription:
    url: "https://subs.domain.com"
    user: "admin"
    password: "admin"
  db:
    de:
      path: de/x-ui.db
      address: "https://192.168.80.7:12345"
      inbound: 1
      panel_path: "/abcdefg/"
    nl:
      path: nl/x-ui.db
      address: "https://192.168.80.7:54321"
      inbound: 1
      panel_path: "/gfedcba/"
  default:
    - total_gb=10
    - duration_days=30
    - reset_days=0
  welcome:
    en: "Welcome, this is your completely free subscription VPN, you have {quota}. Enjoy!\n\n{sub_url}\n\nDo you need help to install the app? Call this command /help"
  status:
    en: "This is your VPN subscription: \n\n{sub_url}\n\n You have used {used_gb} GB of {total_gb} GB, expires on {expiration_date}\nDo you need help? Call this command /help"
  quota_warning:
    en: 
  quota_exceeded:
    en: "You have exceeded your quota of {total_gb} GB.\nYour access will be restored on the next renewal date.\n\nExpires on: {expiration_date}\nDo you need more data? Call this command /help"
  help:
    en: |
      *Instructions:*
      1. Copy the subscription link provided above.
      2. Install and open Hiddify.
      3. New profile > Add from clipboard.
  trial_end:
    en: "Your free trial has ended. To continue using the VPN service, please consider subscribing to one of our paid plans. For more information, contact us."
  contact:
    en: "For more information about our paid plans and pricing, please contact us at @HiddifySupport."